### ISSUE TITLE
Southern Opportunity Regional Center LLC-德克萨斯-ID1419651808

### ISSUE THREAD

**Issue by flyeven** [flybiz/eb5#1040]
http://bbs.fcgvisa.com/t/topic/14890
EB5 区域中心名称：Southern Opportunity Regional Center LLC
EB5 区域中心英文名称：Southern Opportunity Regional Center LLC
所在州：德克萨斯/Texas
区域中心ID：ID1419651808
区域中心网站： 

> [飞出国投资移民](http://www.flyabroad.biz/) - 2016 EB5 美国区域中心。

**Comment by fly61** [comment]
# 南方机会区域中心区域中心-德州-ID1419651808

## 简介

南方机会区域中心是由美国移民局批准的区域中心。2014年10月27日在德州和路易斯安那州获得批准投资并创造就业机会。

## 团队
- **投资公司：** Barnhart Economic Services LLC
- **证券/律师：** Homeier & Law, P.C.

## 项目
- 伍德维尔TX锯木厂

> [飞出国投资移民](http://www.flyabroad.biz/)-2016 EB5 美国区域中心。

https://eb5projects.com/profile/regional-center/884-southern-opportunity-regional-center-llc
