### ISSUE TITLE
美国区域中心 - 拉斯维加斯-内华达-ID1318651173

### ISSUE THREAD

**Issue by flyeven** [flybiz/eb5#115]
http://bbs.fcgvisa.com/t/topic/13963 
EB5 区域中心名称：美国区域中心 - 拉斯维加斯
EB5 区域中心英文名称：American Regional Center-Las Vegas, LLC 
所在州：内华达/Nevada
区域中心ID：ID1318651173
区域中心网站： 

> [飞出国投资移民](http://www.flyabroad.biz/) - 2016 EB5 美国区域中心。

**Comment by fly61** [comment]
# 美国区域中心-拉斯维加斯-内达华-ID1318651173

**区域中心网站：** http://www.lasvegasarc.com/  

## 简介

美国区域中心 – 拉斯维加斯位于美国内华达州的克拉克县内，其当之无愧的地标则是著名的拉斯维加斯大道。拉斯维加斯大道每年吸引了超过4400万来自各地的游客。这里坐落了豪华的度假酒店更每晚提供顶级的娱乐和表演。不只如此，内华达州拥有着闻名世界的自然景观，都与克拉克县在合理的车程之内。克拉克县内还有完善的城市设施，让这一地带不仅成为了旅游胜地，更是居住的首选。

优良的商业机会和美丽的天然环境自然让拉斯维加斯成为了EB-5 投资移民的最好选择，而这也是我们发挥特长的领域。我们的管理团队拥有20年以上的商业地产经验并只与顶尖的移民律师合作以确保每位投资人成功获得永久居留权。

## 团队
- **创办人：** 雷龙升
- **经理：** Alina Lo

## 项目
- 疗养中心
- 医疗大楼
- 度假酒店

> [飞出国投资移民](http://www.flyabroad.biz/)-2016 EB5 美国区域中心。

http://www.lasvegasarc.com/cn/
