### ISSUE TITLE
美国 EB-5 夏洛特优选特许学校 项目介绍-CCC-Education Fund of America

### ISSUE THREAD

**Issue by fly61** [flybiz/eb5#1179]
教育基金SE区域中心-北卡罗来纳-ID1510551754 #450

http://bbs.fcgvisa.com/t/eb-5-ccc-education-fund-of-america/16872
## 夏洛特优选特许学校 EB5 项目

**夏洛特优选特许学校 项目介绍（Project Description）：** 琳达·克鲁兹是夏洛特优选特许学校的创始人，她表示该校等候入学的学生人数已经超过250人。该校对当地社区所形成的影响十分显著，因为当地的学生都对学习产生了浓厚的兴趣。

三位EB-5投资人共为这所学校投资150万美元。

学校将100%通过债券融资，这部分资金将用于购买土地及新校区的建设。EB-5投资人的资金将被用于偿还债券贷款——即过桥贷款。EB-5资金用于偿还过桥贷款是美国移民局许可的行为。

根据预计，学校利用债券筹集到收购学校的资金之后，就将返还投资人50万美元的本金。在美国，利用债券获得的特许学校融资已经超过50亿美元。在移民局对I-829申请做出裁决之前，学校不会返还EB-5投资人的本金。

CCC致力于通过科学，技术，工程，艺术和数字一体化改造学校，使个人潜能最大化，并确保学生用最好的设备通过创新，协作和创造性地解决问题来面对全球性挑战。

**项目中文名称：** 夏洛特优选特许学校  
**项目英文名称：** CCC  
**归属区域中心：** 美国教育基金-北卡罗来纳  
**开始日期（Opened）：** 2014年7月24日  
**项目需要的资金（FUNDING NEEDED）：** $3.6（MIO）  
**EB5 募集资金（EB5 FUNING）：** $1.5 (MIO)  
**申请人投资额（INVESTMENT AMOUNT）：** $500,000  
**需要的 EB-5 投资人数（EB-5 INVESTORS）：** 3  
**项目发行费（SUBSCRIPTION FEE）：**  
**每个投资创造的就业：** 12.6  
**项目创造的总就业：** 38  
**行业（CATEGORY）：** 建筑 Construction  
**子行业(SUB-CATEGORY)：** 商业及办公楼建筑施工 Commercial and Institutional Building Construction  
**投资结构（STRUCTURE）：**  
**参与人数（AMOUNT OF EB-5 INVESTORS）：**  
**预计期限（EXPECTED MATURITY）：**  
**预期回报（EXPECTED RETURN）：**  
**项目是否有主产权（PRINCIPAL EQUITY IN PROJECT）：**  
**项目是否有 I-526 获批：**  
**区域中心是否有 I-526 获批：**  
**区域中心是否有 I-829 获批：**  
**项目所在州（STATE）：** 北卡罗来纳 North Carolina

> 美国投资移民 EB5 相关信息由[飞出国](http://fcgvisa.com)整理自 uscis & iiusa & EB5Projects & eb5investors

https://eb5projects.com/projects/807-charlotte-choice-charter-school 

http://blog.sina.com.cn/s/blog_c0d62fe80102uzqw.html

http://www.charlottechoicecharter.org/apps/pages/index.jsp?uREC_ID=331347&type=d&pREC_ID=947209

**Comment by flyeven** [comment]
1. 关闭的项目不用整理了，提高有效开放项目的整理效率。
2. 关闭项目要在显耀位置处标注该项目关闭的状态及关闭的时间，关闭的项目对申请人已经没有任何意义。
3. eb5项目在 github 里不用贴 rc 标签。

思考如何做最有价值，最有效率是很重要的。
