### ISSUE TITLE
美国 EB-5 圣克劳德预备学校 项目介绍-St. Cloud Prep-Education Fund of America

### ISSUE THREAD

**Issue by fly61** [flybiz/eb5#1181]
[教育基金SE区域中心-佛罗里达-ID1510551754](https://github.com/flybiz/eb5/issues/448)

http://bbs.fcgvisa.com/t/eb-5-st-cloud-prep-education-fund-of-america/16890
## 圣克劳德预备学校 EB5 项目

**圣克劳德预备学校 项目介绍（Project Description）：**

圣克劳德预备学校免费为佛罗里达州的kindergarten-8年级的学生提供服务。

该学校为学生提供了具有挑战性的，有支持性的学习环境，培养学生高道德价值观，个性发展，领导力，社交成长和智力发展，促进每一位学生的成功。

**项目中文名称：** 圣克劳德预备学校  
**项目英文名称：** Saint Cloud Preparatory Academy  
**归属区域中心：** 美国教育基金-佛罗里达 Education Fund of America-Florida  
**开始日期（Opened）：** 2014年7月16日  
**项目需要的资金（FUNDING NEEDED）：** $5.4（MIO）  
**EB5 募集资金（EB5 FUNING）：** $2 (MIO)  
**申请人投资额（INVESTMENT AMOUNT）：** $500,000  
**需要的 EB-5 投资人数（EB-5 INVESTORS）：** 4  
**项目发行费（SUBSCRIPTION FEE）：**  
**每个投资创造的就业：** 12.7  
**项目创造的总就业：** 51  
**行业（CATEGORY）：** 建筑 Construction 
**子行业(SUB-CATEGORY)：** 商业及办公楼建筑施工 Commercial and Institutional Building Construction  
**投资结构（STRUCTURE）：**  
**参与人数（AMOUNT OF EB-5 INVESTORS）：**  
**预计期限（EXPECTED MATURITY）：**  
**预期回报（EXPECTED RETURN）：**  
**项目是否有主产权（PRINCIPAL EQUITY IN PROJECT）：**  
**项目是否有 I-526 获批：**  
**区域中心是否有 I-526 获批：**  
**区域中心是否有 I-829 获批：**  
**项目所在州（STATE）：** 佛罗里达 Florida

> 美国投资移民 EB5 相关信息由[飞出国](http://fcgvisa.com)整理自 uscis & iiusa & EB5Projects & eb5investors

https://eb5projects.com/projects/805-saint-cloud-preparatory-academy

http://www.saintcloudprep.org/

http://www.edufundamericacn.com/soldout_page_2.html

**Comment by flyeven** [comment]
规律：网站链接里有项目名称的，都是已经关闭的，例如 `https://eb5projects.com/projects/805-saint-cloud-preparatory-academy` 。

Opened: July 16, 2014

Closed: July 03, 2016

google 里 “Saint Cloud Preparatory Academy EB-5”

可以中文介绍搜到： http://www.goodhopevisa.cn/shenfen/27.html

里面内容很全，加收eb5projects，这类大概5-10分钟可以整理一个很完整的帖子。
