### ISSUE TITLE
美国 eb-5 克利夫兰大学园区 项目介绍-One University Circle

### ISSUE THREAD

**Issue by fly61** [flybiz/eb5#1261]
克利夫兰国际基金有限公司-俄亥俄-ID1031910169 #305 

http://bbs.fcgvisa.com/t/eb-5-one-university-circle/17285
## 克利夫兰大学园区 EB5 项目

**克利夫兰大学园区 项目介绍（Project Description）：**

俄亥俄州的克利夫兰——当地的开发商想要在三月开发一块土地用于在大学园区建设一个20层的公寓大楼，这块土地之前是被克利夫兰儿童博物馆占用的。

这座公寓大楼将包括280个住宅，一个车库和位于一楼的小酒馆和市场。开发商期望在2018年开始运营公寓。

**项目中文名称：** 一个大学园区  
**项目英文名称：** One University Circle  
**归属区域中心：** 克利夫兰国际基金有限公司 Cleveland International Fund, Ltd  
**开始日期（Opened）：**  
**项目需要的资金（FUNDING NEEDED）：** $118.5（MIO）  
**EB5 募集资金（EB5 FUNING）：** $12.5 (MIO)  
**申请人投资额（INVESTMENT AMOUNT）：** $500,000  
**需要的 EB-5 投资人数（EB-5 INVESTORS）：** 25  
**项目发行费（SUBSCRIPTION FEE）：**  
**每个投资创造的就业：** 43.5  
**项目创造的总就业：** 1088.6  
**行业（CATEGORY）：** 建筑 Construction  
**子行业(SUB-CATEGORY)：** 新多户型住房建筑（除出售建设者）New Multifamily Housing Construction (except For-Sale Builders)  
**投资结构（STRUCTURE）：**  
**参与人数（AMOUNT OF EB-5 INVESTORS）：**  
**预计期限（EXPECTED MATURITY）：**  
**预期回报（EXPECTED RETURN）：**  
**项目是否有主产权（PRINCIPAL EQUITY IN PROJECT）：**  
**项目是否有 I-526 获批：** 否  
**区域中心是否有 I-526 获批：** 否  
**区域中心是否有 I-829 获批：** 否  
**项目所在州（STATE）：** 俄亥俄州 Ohio

> 美国投资移民 EB5 相关信息由[飞出国](http://fcgvisa.com)整理自 uscis & iiusa & EB5Projects & eb5investors

https://eb5projects.com/projects/736-one-university-circle

http://www.cleveland.com/business/index.ssf/2016/02/one_university_circle_apartmen_1.html

**Comment by flyeven** [comment]
One University Circle 翻为 “一个大学园区” 有些呆板，这个项目在 克利夫兰 地区（地图有显示，区域中心也在这里），可以翻译为 克利夫兰大学园区 EB-5 项目，更容易被接受。“一个”给人的感觉是量词，而不是名词。

**子行业(SUB-CATEGORY)：** 新多户型住房建筑（**除出售建设者**）New Multifamily Housing Construction (except For-Sale Builders)      

百度和词霸的翻译： 新的多户住房建设（除出售商）
有道翻译： 新多户住房建设(待售的建造者除外)

修改，后面注意。

except For-Sale Builders 翻译为“除出售建设者”，不符合中文表达习惯，建设者还被“出售”？“除出售建设者”又怎么解释？

网上有对这个项目的介绍，可以从一些文章里总结一些有价值内容：

http://www.cleveland.com/business/index.ssf/2016/02/one_university_circle_apartmen_1.html
https://eb5projects.com/updates/project_updates/1431

如果没有去总结，只梳理 eb5projects 信息，需要提高效率。
