### ISSUE TITLE
阿什克罗夫特/沙利文/ Baybridge大西洋中部经济开发中心-马里兰-ID1426251890

### ISSUE THREAD

**Issue by flyeven** [flybiz/eb5#158]
http://bbs.fcgvisa.com/t/topic/14006 
EB5 区域中心名称：阿什克罗夫特/沙利文/ Baybridge大西洋中部经济开发中心
EB5 区域中心英文名称：Ashcroft/Sullivan/Baybridge Mid-Atlantic Economic Development Center 
所在州：马里兰/Maryland
区域中心ID：ID1426251890
区域中心网站： 

> [飞出国投资移民](http://www.flyabroad.biz/) - 2016 EB5 美国区域中心。

**Comment by fly61** [comment]
# 阿什克罗夫特/沙利文/Baybridge大西洋中部经济开发中心-马里兰-ID1426251890

## 简介

阿什克罗夫特沙利文经济发展中心2015年希望从国土安全部的美国公民和公民服务(USCIS)得到联邦政府的批准成为EB-5区域中心试点项目中的EB-5区域中心。

作为联邦政府指定的区域中心，我们的使命是在大西洋中部和新英格兰地区创造新的就业机会，扩大经济生产力，帮助外国投资者和他们的家人获得永久居留权。

## 团队
- **董事长：**John Ashcroft，Michael Sullivan
- **阿什克罗夫特集团首席执行官：**David Ayres
- **处理交易事项的人员：**Debbie A. Klis
- **合伙人：**David Boucher，Joseph Fitzpatrick，Brian Foster，Brett Griffith

## 项目
- 雷诺尔公寓
- 新英格兰运动村

**区域中心网站：**http://aseb5.com/ 

> [飞出国投资移民](http://www.flyabroad.biz/)-2016 EB5 美国区域中心。

https://eb5projects.com/profile/regional-center/979-ashcroft-sullivan-baybridge-mid-atlantic-economic-development-cent

http://aseb5.com/
