### ISSUE TITLE
Baypointe EB5区域中心-科拉巴马-ID1435252136

### ISSUE THREAD

**Issue by flyeven** [flybiz/eb5#168]
http://bbs.fcgvisa.com/t/topic/14016 
EB5 区域中心名称：Baypointe EB5区域中心
EB5 区域中心英文名称：Baypointe EB5 Regional Center, LLC 
所在州：科拉巴马/Alabama
区域中心ID：ID1435252136
区域中心网站： http://www.baypointeeb5.com/

> [飞出国投资移民](http://www.flyabroad.biz/) - 2016 EB5 美国区域中心。

**Comment by fly61** [comment]
# Baypointe EB-5区域中心-阿拉巴马-ID1435252136

## 简介

该区域中心目的就是帮助外来投资者获取永久居留权。项目涉及辅助生活设施，混合用途设施，多单元住宅公寓，餐厅，饮食服务等等。

## 项目
- 阿巴科海湾重建
- 阿拉巴马州豪华城市公寓
- Baptist健康医疗体系
- 迈阿密全景塔
- 亨德森度假酒店

> [飞出国投资移民](http://www.flyabroad.biz/)-2016 EB5 美国区域中心。

https://eb5projects.com/profile/regional-center/988-baypointe-eb5-regional-center-llc
