### ISSUE TITLE
California One Investment Center, LLC -加利福尼亚-ID1326051211

### ISSUE THREAD

**Issue by flyeven** [flybiz/eb5#209]
http://bbs.fcgvisa.com/t/topic/14057 
EB5 区域中心名称：California One Investment Center, LLC 
EB5 区域中心英文名称：California One Investment Center, LLC 
所在州：加利福尼亚/California
区域中心ID：ID1326051211
区域中心网站： http://coiccenter.com/

> [飞出国投资移民](http://www.flyabroad.biz/) - 2016 EB5 美国区域中心。

**Comment by fly61** [comment]
# California One Investment Center, LLC-加利福尼亚-ID1326051211

## 简介

公司始建于2013年，位于美国南加州美丽的工业城市，许多世界500强企业都把他们的总部和分支设立在这里。我们有专业知识和丰富的经验，还有杰出的管理团队。确保客户利益至上。

## 项目
- 三位一体物流控股有限责任公司
- 第三方物流
- 节能锅炉

> [飞出国投资移民](http://www.flyabroad.biz/)-2016 EB5 美国区域中心。

http://coiccenter.com/?page_id=56
