### ISSUE TITLE
Farm for America Regional Center 美国农场区域中心-华盛顿-ID1031910018

### ISSUE THREAD

**Issue by flyeven** [flybiz/eb5#488]
http://bbs.fcgvisa.com/t/topic/14337
EB5 区域中心名称：Farm for America Regional Center 美国农场区域中心
EB5 区域中心英文名称：Farm for America Regional Center 
所在州：华盛顿/Washington
区域中心ID：ID1031910018
区域中心网站： 

> [飞出国投资移民](http://www.flyabroad.biz/) - 2016 EB5 美国区域中心。

**Comment by fly61** [comment]
# 美国农场区域中心-加利福尼亚-ID1031910018

## 简介

2011年5月2日美国农场正式被移民局指定为区域中心。FFA一直在积极寻求机会，促进经济增长，提高区域生产力，创造就业机会。其目的是更加促进经济的增长，创造更多的就业机会。为了实现这一目标，FFA欢迎各个赞助商提供投资。

## 优势
- 有绿卡保障
- 还款机制有利

## 项目
- 爱蕾特琪红酒庄园

**区域中心网站：** http://www.ffa-rc.com/

> [飞出国投资移民](http://www.flyabroad.biz/)-2016 EB5 美国区域中心。

http://www.ffa-rc.com/
