### ISSUE TITLE
GO USA EB-5区域中心-伊利诺斯-ID1423151851

### ISSUE THREAD

**Issue by flyeven** [flybiz/eb5#531]
http://bbs.fcgvisa.com/t/topic/14380
EB5 区域中心名称：GO USA EB-5区域中心
EB5 区域中心英文名称：GO USA EB-5 Regional Center, LLC  
所在州：伊利诺斯/Illinois
区域中心ID：ID1423151851
区域中心网站： 

> [飞出国投资移民](http://www.flyabroad.biz/) - 2016 EB5 美国区域中心。

**Comment by fly37** [comment]
http://bbs.fcgvisa.com/t/go-usa-eb-5-id1423151851/14380/2

## GO USA EB-5 区域中心  GO USA EB-5 Regional Cente,LLC-ID1423151851

### 区域中心简介

透过GO EB5 RC区域中心进行投资，合资格的外国人将可为其本人及其家庭成员以EB-5计划申请美国居民的身份。该计划受美国公民及移民服务局（“USCIS”）管理。

GO EB5 RC区域中心的目标是透过投资在建造业，酒店业和餐饮业，集中推动在芝加哥及伊利诺伊州大都巿区的经济发展及就业机会。

GO EB5 RC区域中心，联同一独立的投资监事，将确保1）资本将被投放于一个获批核的，新的商业机构2）符合对创造就业机会的有关规定。上述两点皆是确保EB -5获得成功的关键。

### 开发商

GO EB5 RC区域中心将由Scott David Greenberg, 葛霖波先生出任主席及行政总裁。葛霖波先生是一位在房地产方面经验丰富而且具远见的成功人仕。他曾设计，建立及经营过很多荣获奖项的酒店，零售及综合型的建筑。葛霖波先生的30年经验遍布在低层或高层建筑物，项目开发及融资。在设计方面，葛霖波先生是一个完美主义者并设计了很多具地表性的建筑物，包括芝加哥theWit酒店。

### 包含项目
- 芝加哥市高级公寓EB-5项目 Smash Residential

> [飞出国投资移民](http://www.flyabroad.biz/)-2016 EB5 美国区域中心。

http://goeb5rc.com/
