### ISSUE TITLE
Golden Opportunity 区域中心-加利福尼亚-ID1209050631

### ISSUE THREAD

**Issue by flyeven** [flybiz/eb5#537]
http://bbs.fcgvisa.com/t/topic/14386
EB5 区域中心名称：Golden Opportunity 区域中心
EB5 区域中心英文名称：Golden Opportunity Regional Center  
所在州：加利福尼亚/California
区域中心ID：ID1209050631
区域中心网站： http://www.gorc-eb5.com/

> [飞出国投资移民](http://www.flyabroad.biz/) - 2016 EB5 美国区域中心。

**Comment by fly61** [comment]
# Golden Opportunity 区域中心-加利福尼亚-ID1209050631

## 简介

该区域中心在2014年9月19日被批准为区域中心。该区域中心将重点推动建设促进经济增长的建筑(NAICS - 236)，护理和住宅保健设施(NAICS - 623)，酒店(赌场酒店除外)和汽车旅馆(NAICS - 72111)。

## 开发商

帕西菲卡公司 Pacifica Company

## 项目
- 圣地亚哥海湾一期
- 格罗弗海滩别墅
- 加利福尼亚州斯普林河海岸
- 皮尔南酒店
- 文图拉万豪酒店

**区域中心网站：** http://www.gorc-eb5.com/

> [飞出国投资移民](http://www.flyabroad.biz/)-2016 EB5 美国区域中心。

http://www.gorc-eb5.com/

https://eb5projects.com/profile/regional-center/856-golden-opportunity-regional-center#naic
