### ISSUE TITLE
林氏纽约 EB-5区域中心-纽约-ID1121350259

### ISSUE THREAD

**Issue by flyeven** [flybiz/eb5#645]
http://bbs.fcgvisa.com/t/topic/14494
EB5 区域中心名称：林氏纽约 EB-5区域中心
EB5 区域中心英文名称：Lam NYC EB-5 Fund Regional Center, LLC  
所在州：纽约/New York
区域中心ID：ID1121350259
区域中心网站： http://lamnyceb5.com/zh-hans/

> [飞出国投资移民](http://www.flyabroad.biz/) - 2016 EB5 美国区域中心。

**Comment by fly61** [comment]
# 林氏纽约EB-5区域中心-纽约-ID1121350259

## 简介

林氏纽约EB-5基金有限责任公司，简称"林氏EB-5"是获美国移民局批准的区域中心，位于世界上最为繁荣和多元的纽约市。作为区域中心，林氏EB-5通过EB-5投资移民计划，协助外国投资者将资金投资于林氏集团开发的房地产项目，从而获取美国永久居留权。

林氏纽约区域中心（英文为LAM NYC EB-5 FUND REGIONAL CENTER)是我们本着提振我们挚爱的纽约市的房地产投资与为有意移民美国的投资者提供最佳项目支持的双重使命而建立的。

与很多基金管理人相比，林氏集团不仅是管理人，还是自有资金的投资人。我们青睐投资那些不受地产周期性影响的有持续发展潜力的长期项目。

林氏集团是由林家在1970年创立，负责人是首席执行官兼董事长林建中先生。林先生最初是从香港移民到美国并追求美国梦，作为一个成功的企业家和纽约市酒店大亨在纽约市打造了自己的名字。林氏纽约区域中心的团队里有著名的移民律师，顾问，及房地产专家。我们也保持与开发团队及融资团队紧密无间的协调，以保证项目的进行密切配合EB-5的移民时间表。

林氏纽约区域中心已经成功募集了两个EB-5项目，包括位于30 Fletcher和213 Pearl的两个酒店项目。林氏纽约区域中心将不断提供林氏集团所开发的投资项目供EB-5投资人参与。

林氏纽约EB-5区域中心的使命是为在区域中心经营地域范围许可的“目标就业区”内的开发项目募集资金。这些项目通常有商场，酒店，餐厅，公寓，疗养院和办公楼等。

## 团队
- **负责人及常务董事：** 林建中
- **总监：** Jeffery Lam 林伟鸿先生是Lam Generation的创始人及首席执行官
- **法律顾问：** Julie Cho
- **EB-5项目 董事执行官：** 张彤

## 项目
- 1205百老汇维珍酒店
- 林氏集团213珍珠街
- 弗莱彻街万豪酒店
- 林氏集团25街复兴城酒店

> [飞出国投资移民](http://www.flyabroad.biz/)-2016 EB5 美国区域中心。

https://eb5projects.com/profile/regional-center/484-lam-nyc-eb-5-fund-llc#projects

http://lamnyceb5.com/zh-hans/
