### ISSUE TITLE
美国生活有限公司- 雷克伍德区域中心-华盛顿-ID1031910098

### ISSUE THREAD

**Issue by flyeven** [flybiz/eb5#92]
http://bbs.fcgvisa.com/t/topic/13939 
EB5 区域中心名称：美国生活有限公司- 雷克伍德区域中心
EB5 区域中心英文名称：American Life, Inc. - Lakewood Regional Center 
所在州：华盛顿/Washington
区域中心ID：ID1031910098
区域中心网站： 

> [飞出国投资移民](http://www.flyabroad.biz/) - 2016 EB5 美国区域中心。

**Comment by fly61** [comment]
# 美国生活有限公司-雷克伍德区域中心-华盛顿-ID1031910098

**区域中心网站：** http://amlife.us/

## 简介

美国生活公司是美国移民局最早审核批准成立的EB-5区域中心之一，是美国所有移民中心里面运行历史最悠久，也是最稳定的EB-5区域中心之一。目前，美国生活公司在全美管理9个经联邦政府批准的EB-5区域中心，其中包括亚特兰大，迈阿密，纽约州北部，华盛顿州西部区域三个中心（西雅图，莱克伍德和塔科马），和南加州的三个区域中心。

美国生活公司不仅是USCIC授权的区域中心，同时也是一家综合性的房地产开发和投资公司。区域中心受美国USCIC的授权与严格监管。区域中心即为开发商，使得区域中心以最大限度监管项目的实施运作与资金流动，美国生活公司现已发展成大西雅图地区规模最大的土地所有人之一，其旗下管理520多万平方英尺的土地和360万平方英尺的建筑。公司的开发项目包括一系列混合用途的商业空间，如办公楼、酒店、仓库、制造业及零售地点；成本价值逾近10亿美元。

目前，美国生活公司在全美管理9个经联邦政府批准的EB-5区域中心，其中包括亚特兰大，迈阿密，纽约州北部，华盛顿州西部地区三个中心（西雅图、莱克伍德和塔科马），和南加州的三个区域中心。 美国生活公司自成立以来，已成功操作了50多个商业地产EB-5项目。到2014年年底为止：

1400多户家庭I-526获批
750多户家庭I-829获批

据悉，美国公司的项目在美国移民局获取绿卡数量目前是最多的。在与美国移民局 (USCIS) 的工作中，美国生活公司不但在业界和政府一直享有良好信誉。

## 团队
- **投资商：** Lincoln Stone
- **合作伙伴：** Stone Grzegorek & Gonzalez LLP，American Life, Inc  

## 项目
- 霍姆伍德希尔顿酒店项目
- 加州洛杉矶市万豪酒店
- Riverside County滨江县项目
- 玛驰空军商业园开发项目
- Home Plate项目
- 万怡万豪酒店项目

> [飞出国投资移民](http://www.flyabroad.biz/)-2016 EB5 美国区域中心。

http://amlife.us/

http://www.jcos.ca/eb-5%E7%AE%80%E4%BB%8B/%E7%BE%8E%E5%9B%BD%E7%94%9F%E6%B4%BB%E5%8C%BA%E5%9F%9F%E4%B8%AD%E5%BF%83/
